base_app/urls.py
from django.urls import path
from .views import base_app_view, add_review

app_name = 'base_app'

urlpatterns = [
    path('', base_app_view, name='base_app_view'),
    path('review/', add_review, name='add_review')
]

manager/urls.py
from django.urls import path
from .views import reservations_list, update_reservation, contact_list, \
    update_contact, main_menu_list, add_dish, \
    update_dish, delete_dish, add_category, \
    update_category, delete_category, add_special

urlpatterns = [
    path('reservations/', reservations_list, name='reservations_list'),
    path('reservations/update/<int:pk>/', update_reservation, name='update_reservation'),
    path('contacts/', contact_list, name='contact_list'),
    path('contacts/update/<int:pk>/', update_contact, name="update_contact"),
    path('menu/main/', main_menu_list, name="main_menu_list"),
    path('menu/main/add/', add_dish, name="add_dish"),
    path('menu/main/update/<int:pk>/', update_dish, name="update_dish"),
    path('menu/main/delete/<int:pk>/', delete_dish, name="delete_dish"),
    path('menu/category/add/', add_category, name="add_category"),
    path('menu/category/update/<int:pk>/', update_category, name="update_category"),
    path('menu/category/delete/<int:pk>/', delete_category, name="delete_category"),
    path('menu/special/add/', add_special, name="add_special"),
    path('menu/special/update/<int:pk>/', update_dish, name="update_special"),
    path('menu/special/delete/<int:pk>/', delete_dish, name="delete_special"),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from account.views import logout_view, login_view, registration_view
from base_app.views import add_review


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),

    path('admin/', admin.site.urls),
    path('', include("base_app.urls", namespace='base_app')),

    path('manager/', include('manager.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base_app/models.py
import datetime

from django.db import models
from uuid import uuid4
from os import path
from django.core.validators import RegexValidator

class CategoryDish(models.Model):
    name = models.CharField(max_length=50, unique=True, db_index=True)
    is_visibility = models.BooleanField(default=True)
    position = models.PositiveIntegerField(unique=True)

    class Meta:
        ordering = ("position", )

    def __str__(self):
        return f"{self.name}: {self.position}"


class Dish(models.Model):

    def get_file_name(self, filename):
        ext = filename.strip().split('.')[-1]
        filename = f'{uuid4()}.{ext}'
        return path.join("images/dishes", filename)

    category = models.ForeignKey(CategoryDish, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, unique=True)
    ingredients = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to=get_file_name, default='images/dishes/d3422c5a-633f-4c20-9873-fb9f5e774dde.png')
    description = models.TextField(blank=True)
    dish_order = models.PositiveIntegerField()
    is_visibility = models.BooleanField(default=True)
    is_special = models.BooleanField(default=False)

    class Meta:
        ordering = ("dish_order",)

    def __str__(self):
        return f"{self.title}: {self.price}"

class Reservation(models.Model):
    mobile_regex = RegexValidator(regex=r'^(\d{3}[- .]?){2}\d{4}$', message='Phone in format xxx xxx xxxx')

    name = models.CharField(max_length=50, db_index=True)
    email = models.EmailField()
    phone = models.CharField(max_length=15, validators=[mobile_regex])
    date = models.DateField()
    time = models.TimeField()
    count_people = models.PositiveIntegerField()
    message = models.TextField(max_length=500, blank=True)
    is_processed = models.BooleanField(default=False)

    class Meta:
        ordering = ('-date', '-time',)

    def __str__(self):
        return f'{self.name}, {self.email}, {self.phone}'

class Contact(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField(max_length=500)
    upload = models.DateTimeField(auto_now_add=True)
    is_processed = models.BooleanField(default=False)

    class Meta:
        ordering = ('-upload', )

    def __str__(self):
        return f'{self.subject} ({self.name}, {self.email})'

class Event(models.Model):
    def get_file_name(self, filename):
        ext = filename.strip().split('.')[-1]
        filename = f'{uuid4()}.{ext}'
        return path.join("images/dishes", filename)

    title = models.CharField(max_length=50, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to=get_file_name)
    description = models.TextField(max_length=500)
    list1 = models.CharField(max_length=200)
    list2 = models.CharField(max_length=200)
    list3 = models.CharField(max_length=200)
    description2 = models.TextField(max_length=500)
    position = models.PositiveIntegerField(unique=True)

    class Meta:
        ordering = ('position',)

    def __str__(self):
        return f'{self.title}'

class Gallery(models.Model):
    def get_file_name(self, filename):
        ext = filename.strip().split('.')[-1]
        filename = f'{uuid4()}.{ext}'
        return path.join("images/gallery", filename)

    num = models.PositiveIntegerField(unique=True)
    image = models.ImageField(upload_to=get_file_name)

    def __str__(self):
        return f'{self.num}'

class Chief(models.Model):
    def get_file_name(self, filename):
        ext = filename.strip().split('.')[-1]
        filename = f'{uuid4()}.{ext}'
        return path.join("images/chief", filename)

    surname = models.CharField(max_length=50, db_index=True)
    name = models.CharField(max_length=50)
    post = models.CharField(max_length=100)
    image = models.ImageField(upload_to=get_file_name)
    twitter = models.URLField()
    facebook = models.URLField()
    instagram = models.URLField()

    class Meta:
        ordering = ('post', )

    def __str__(self):
        return f'{self.surname} {self.name} - {self.post}'

class Reviews(models.Model):
    def get_file_name(self, filename):
        ext = filename.strip().split('.')[-1]
        filename = f'{uuid4()}.{ext}'
        return path.join("images/reviews", filename)

    name = models.CharField(max_length=50)
    post = models.CharField(max_length=50)
    image = models.ImageField(upload_to=get_file_name, default='images/dishes/d3422c5a-633f-4c20-9873-fb9f5e774dde.png')
    rating = models.PositiveIntegerField()
    review = models.TextField(max_length=300)
    upload = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-upload',)

    def __str__(self):
        return f'{self.name}, rating - {self.rating}'

base_app/views.py
from django.shortcuts import render, redirect
from .models import Dish, CategoryDish, Event, Gallery, Chief, Reviews
from .form import FormReservation, FormContact, FormReview

def base_app_view(request):
    if request.method == 'POST':
        form_reservation = FormReservation(request.POST)
        form_contact = FormContact(request.POST)
        if form_reservation.is_valid():
            form_reservation.save()
            return redirect('/')
        elif form_contact.is_valid():
            form_contact.save()
            return redirect('/')

    form_reservation = FormReservation()
    form_contact = FormContact()
    dishes = Dish.objects.filter(is_visibility=True, is_special=False).order_by('dish_order')
    categories = CategoryDish.objects.filter(is_visibility=True).order_by('position')
    special = Dish.objects.filter(is_visibility=True, is_special=True).order_by('dish_order')
    events = Event.objects.filter().order_by('position')
    gallery = Gallery.objects.order_by('?')[:8]
    chiefs = Chief.objects.order_by('?')[:3]
    reviews = Reviews.objects.order_by('?')[:6]
    return render(request, 'base_app.html', context={
        'dishes': dishes,
        'categories': categories,
        'special': special,
        'form_reservation': form_reservation,
        'form_contact': form_contact,
        'events': events,
        'gallery': gallery,
        'chiefs': chiefs,
        'reviews': reviews,
    })

def add_review(request):
    if request.method == 'POST':
        form_review = FormReview(request.POST, request.FILES)
        if form_review.is_valid():
            form_review.save()
            return redirect('base_app:base_app_view')

    form_review = FormReview()
    return render(request, 'add_review.html', context={"form_review": form_review})

base_app/templates/add_review.html
    {% extends 'index.html' %}

    {% block content %}
<!-- ======= Leave feedback Section ======= -->
    <section id="book-a-table" class="book-a-table">
      <div class="container">

        <div class="section-title">
          <h2>Leave a <span>Feedback</span></h2>
        </div>

        <form method="post" role="form" enctype="multipart/form-data">
            {% csrf_token %}
          <div class="row">
            <div class="col-lg-4 col-md-6 form-group">
              {{ form_review.name }}
              <div class="validate"></div>
            </div>
            <div class="col-lg-4 col-md-6 form-group mt-3 mt-md-0">
              {{ form_review.post }}
              <div class="validate"></div>
            </div>
            <div class="col-lg-4 col-md-6 form-group mt-3 mt-md-0">
                <p><b>Your Photo:</b> </p>{{ form_review.image }}
              <div class="validate"></div>
            </div>
              <div class="col-lg-4 col-md-6 form-group mt-3">
            </div>
            <div class="col-lg-4 col-md-6 form-group mt-3">
              {{ form_review.rating }}
              <div class="validate"></div>
            </div>
          </div>
          <div class="form-group mt-3">
            {{ form_review.review }}
            <div class="validate"></div>
          </div>
          <div class="text-center"><button type="submit">Leave Feedback</button></div>
        </form>

      </div>
    </section>
        <!-- End Leave Feedback Section -->
{% endblock %}

base_app/templates/base_app.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container-fluid">

        <div class="row">

          <div class="col-lg-5 align-items-stretch video-box" style='background-image: url({% static 'assets/img/about.jpg' %});'>
            <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="venobox play-btn mb-4" data-vbtype="video" data-autoplay="true"></a>
          </div>

          <div class="col-lg-7 d-flex flex-column justify-content-center align-items-stretch">

            <div class="content">
              <h3>Eum ipsam laborum deleniti <strong>velit pariatur architecto aut nihil</strong></h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit
              </p>
              <p class="fst-italic">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                magna aliqua.
              </p>
              <ul>
                <li><i class="bx bx-check-double"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
                <li><i class="bx bx-check-double"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
                <li><i class="bx bx-check-double"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>
              </ul>
              <p>
                Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
                velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                culpa qui officia deserunt mollit anim id est laborum
              </p>
            </div>

          </div>

        </div>

      </div>
    </section><!-- End About Section -->

    <!-- ======= Whu Us Section ======= -->
    <section id="why-us" class="why-us">
      <div class="container">

        <div class="section-title">
          <h2>Why choose <span>Our Restaurant</span></h2>
          <p>Ut possimus qui ut temporibus culpa velit eveniet modi omnis est adipisci expedita at voluptas atque vitae autem.</p>
        </div>

        <div class="row">

          <div class="col-lg-4">
            <div class="box">
              <span>01</span>
              <h4>Lorem Ipsum</h4>
              <p>Ulamco laboris nisi ut aliquip ex ea commodo consequat. Et consectetur ducimus vero placeat</p>
            </div>
          </div>

          <div class="col-lg-4 mt-4 mt-lg-0">
            <div class="box">
              <span>02</span>
              <h4>Repellat Nihil</h4>
              <p>Dolorem est fugiat occaecati voluptate velit esse. Dicta veritatis dolor quod et vel dire leno para dest</p>
            </div>
          </div>

          <div class="col-lg-4 mt-4 mt-lg-0">
            <div class="box">
              <span>03</span>
              <h4> Ad ad velit qui</h4>
              <p>Molestiae officiis omnis illo asperiores. Aut doloribus vitae sunt debitis quo vel nam quis</p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Whu Us Section -->

    {% include 'main_menu.html' %}

    {% include 'special_menu.html' %}

    {% include 'events.html' %}

    {% include 'registration.html' %}

    {% include 'galery.html' %}

    {% include 'chief.html' %}

    {% include 'review.html' %}

    {% include 'contact.html' %}

  </main><!-- End #main -->
{% endblock %}

base_app/templates/chief.html
<!-- ======= Chefs Section ======= -->
    <section id="chefs" class="chefs">
      <div class="container">

        <div class="section-title">
          <h2>Our Proffesional <span>Chefs</span></h2>
          <p>Ut possimus qui ut temporibus culpa velit eveniet modi omnis est adipisci expedita at voluptas atque vitae autem.</p>
        </div>

        <div class="row">
            {% for chief in chiefs %}
          <div class="col-lg-4 col-md-6">

            <div class="member">

              <div class="pic"><img src="{{ chief.image.url }}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>{{ chief.name }} {{ chief.surname }}</h4>
                <span>{{ chief.post }}</span>
                <div class="social">
                  <a href="{{ chief.twitter }}"><i class="bi bi-twitter"></i></a>
                  <a href="{{ chief.facebook }}"><i class="bi bi-facebook"></i></a>
                  <a href="{{ chief.instagram }}"><i class="bi bi-instagram"></i></a>
                </div>
              </div>

            </div>

          </div>
            {% endfor %}
        </div>

      </div>
    </section><!-- End Chefs Section -->

base_app/templates/contact.html
<!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container">

        <div class="section-title">
          <h2><span>Contact</span> Us</h2>
          <p>Ut possimus qui ut temporibus culpa velit eveniet modi omnis est adipisci expedita at voluptas atque vitae autem.</p>
        </div>
      </div>

      <div class="map">
        <iframe style="border:0; width: 100%; height: 350px;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" allowfullscreen></iframe>
      </div>

      <div class="container mt-5">

        <div class="info-wrap">
          <div class="row">
            <div class="col-lg-3 col-md-6 info">
              <i class="bi bi-geo-alt"></i>
              <h4>Location:</h4>
              <p>A108 Adam Street<br>New York, NY 535022</p>
            </div>

            <div class="col-lg-3 col-md-6 info mt-4 mt-lg-0">
              <i class="bi bi-clock"></i>
              <h4>Open Hours:</h4>
              <p>Monday-Saturday:<br>11:00 AM - 2300 PM</p>
            </div>

            <div class="col-lg-3 col-md-6 info mt-4 mt-lg-0">
              <i class="bi bi-envelope"></i>
              <h4>Email:</h4>
              <p>info@example.com<br>contact@example.com</p>
            </div>

            <div class="col-lg-3 col-md-6 info mt-4 mt-lg-0">
              <i class="bi bi-phone"></i>
              <h4>Call:</h4>
              <p>+1 5589 55488 51<br>+1 5589 22475 14</p>
            </div>
          </div>
        </div>

        <form method="post" role="form">
            {% csrf_token %}
          <div class="row">
            <div class="col-md-6 form-group">
                {{ form_contact.name }}
            </div>
            <div class="col-md-6 form-group mt-3 mt-md-0">
                {{ form_contact.email }}
            </div>
          </div>
          <div class="form-group mt-3">
              {{ form_contact.subject }}
          </div>
          <div class="form-group mt-3">
            {{ form_contact.message }}
          </div>

          <div class="text-center"><button type="submit">Send Message</button></div>
        </form>

      </div>
    </section><!-- End Contact Section -->

base_app/templates/events.html
<!-- ======= Events Section ======= -->
    <section id="events" class="events">
      <div class="container">

        <div class="section-title">
          <h2>Organize Your <span>Events</span> in our Restaurant</h2>
        </div>

        <div class="events-slider swiper-container">
        {% for event in events %}
          <div class="swiper-wrapper">

            <div class="swiper-slide">
              <div class="row event-item">
                <div class="col-lg-6">
                  <img src="{{ event.image.url }}" class="img-fluid" alt="">
                </div>
                <div class="col-lg-6 pt-4 pt-lg-0 content">
                  <h3>{{ event.title }}</h3>
                  <div class="price">
                    <p><span>${{ event.price }}</span></p>
                  </div>
                  <p class="fst-italic">
                    {{ event.description }}
                  </p>
                  <ul>
                    <li><i class="bi bi-check-circle"></i> {{ event.list1 }}</li>
                    <li><i class="bi bi-check-circle"></i> {{ event.list2 }}</li>
                    <li><i class="bi bi-check-circle"></i> {{ event.list3 }}</li>
                  </ul>
                  <p>
                    {{ event.description2 }}
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->



          </div>
            {% endfor %}
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Events Section -->

base_app/templates/galery.html
<!-- ======= Gallery Section ======= -->
    <section id="gallery" class="gallery">
      <div class="container-fluid">

        <div class="section-title">
          <h2>Some photos from <span>Our Restaurant</span></h2>
          <p>Ut possimus qui ut temporibus culpa velit eveniet modi omnis est adipisci expedita at voluptas atque vitae autem.</p>
        </div>

        <div class="row no-gutters">
            {% for image in gallery %}
          <div class="col-lg-3 col-md-4">

            <div class="gallery-item">

              <a href="{{ image.image.url }}" class="gallery-lightbox">
                <img src="{{ image.image.url }}" alt="" class="img-fluid">
              </a>

            </div>

          </div>
            {% endfor %}
        </div>

      </div>
    </section><!-- End Gallery Section -->

base_app/templates/main_menu.html
<!-- ======= Menu Section ======= -->
    <section id="menu" class="menu">
      <div class="container">

        <div class="section-title">
          <h2>Check our tasty <span>Menu</span></h2>
        </div>

        <div class="row">
          <div class="col-lg-12 d-flex justify-content-center">
            <ul id="menu-flters">
              <li data-filter="*" class="filter-active">Show All</li>
                {% for category in categories %}
                    <li data-filter=".filter-{{ category.name }}">{{ category }}</li>
                {% endfor %}
            </ul>
          </div>
        </div>

        <div class="row menu-container">
            {% for dish in dishes %}
                <div class="col-lg-6 menu-item filter-{{ dish.category.name }}">
            <div class="menu-content">
              <a href="#">{{ dish.title }}</a><span>$ {{ dish.price }}</span>
            </div>
            <div class="menu-ingredients">
              {{ dish.ingredients }}
            </div>
          </div>

            {% endfor %}
        </div>

      </div>
    </section><!-- End Menu Section -->

base_app/templates/registration.html
<!-- ======= Book A Table Section ======= -->
    <section id="book-a-table" class="book-a-table">
      <div class="container">

        <div class="section-title">
          <h2>Book a <span>Table</span></h2>
          <p>Ut possimus qui ut temporibus culpa velit eveniet modi omnis est adipisci expedita at voluptas atque vitae autem.</p>
        </div>

        <form method="post" role="form">
            {% csrf_token %}
          <div class="row">
            <div class="col-lg-4 col-md-6 form-group">
              {{ form_reservation.name }}
              <div class="validate"></div>
            </div>
            <div class="col-lg-4 col-md-6 form-group mt-3 mt-md-0">
              {{ form_reservation.email }}
              <div class="validate"></div>
            </div>
            <div class="col-lg-4 col-md-6 form-group mt-3 mt-md-0">
              {{ form_reservation.phone }}
              <div class="validate"></div>
            </div>
            <div class="col-lg-4 col-md-6 form-group mt-3">
              {{ form_reservation.date }}
              <div class="validate"></div>
            </div>
            <div class="col-lg-4 col-md-6 form-group mt-3">
              {{ form_reservation.time }}
              <div class="validate"></div>
            </div>
            <div class="col-lg-4 col-md-6 form-group mt-3">
              {{ form_reservation.count_people }}
              <div class="validate"></div>
            </div>
          </div>
          <div class="form-group mt-3">
            {{ form_reservation.message }}
            <div class="validate"></div>
          </div>
          <div class="text-center"><button type="submit">Send Message</button></div>
        </form>

      </div>
    </section><!-- End Book A Table Section -->

base_app/templates/review.html
{% load template_tags %}
<!-- ======= Testimonials Section ======= -->
    <section id="testimonials" class="testimonials">
      <div class="container position-relative">

        <div class="testimonials-slider swiper-container" data-aos="fade-up" data-aos-delay="100">
          <div class="swiper-wrapper">
            {% for review in reviews %}
            <div class="swiper-slide">
              <div class="testimonial-item">
                <img src="{{ review.image.url }}" class="testimonial-img" alt="">
                <h3>{{ review.name }}</h3>
                <h4>{{ review.post }}</h4>
                <div class="stars">
                    {% for star in review.rating|range%}
                  <i class="bi bi-star-fill"></i>
                    {% endfor %}
                </div>
                <p>
                  <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                  {{ review.review }}
                  <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                </p>
              </div>
            </div><!-- End testimonial item -->


            {% endfor %}
          </div>
          <div class="swiper-pagination"></div>
        </div>

          <div class="section-title">
              <a href="{% url 'base_app:add_review' %}">
                  <button type="button" class="btn btn-primary btn-sm">Оставить отзыв</button>
              </a>
          </div>
      </div>


      </div>
    </section><!-- End Testimonials Section -->

base_app/templates/special_menu.html
<!-- ======= Specials Section ======= -->
    <section id="specials" class="specials">
      <div class="container">

        <div class="section-title">
          <h2>Check our <span>Specials</span></h2>
          <p>Ut possimus qui ut temporibus culpa velit eveniet modi omnis est adipisci expedita at voluptas atque vitae autem.</p>
        </div>

        <div class="row">
          <div class="col-lg-3">
            <ul class="nav nav-tabs flex-column">
                {% for special in special %}
                    {% if forloop.first %}
                        <li class="nav-item">
                            <a class="nav-link active show" data-bs-toggle="tab" href="#tab-{{ special.id }}">{{ special.title }}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" data-bs-toggle="tab" href="#tab-{{ special.id }}">{{ special.title }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
          </div>
          <div class="col-lg-9 mt-4 mt-lg-0">
            <div class="tab-content">
                {% for item in special %}
                    {% if forloop.first %}
                        <div class="tab-pane active show" id="tab-{{ item.id }}">
                <div class="row">
                  <div class="col-lg-8 details order-2 order-lg-1">
                    <h3>{{ item.title }}</h3>
                    <p class="fst-italic">{{ item.ingredients }}</p>
                      <p>{{ item.description }}</p>
                  </div>
                  <div class="col-lg-4 text-center order-1 order-lg-2">
                    <img src="{{ item.image.url }}" alt="" class="img-fluid">
                  </div>
                </div>
              </div>
                    {% else %}
                        <div class="tab-pane" id="tab-{{ item.id }}">
                <div class="row">
                  <div class="col-lg-8 details order-2 order-lg-1">
                    <h3>{{ item.title }}</h3>
                    <p class="fst-italic">{{ item.ingredients }}</p>
                    <p>{{ item.description }}</p>
                  </div>
                  <div class="col-lg-4 text-center order-1 order-lg-2">
                    <img src="{{ item.image.url }}" alt="" class="img-fluid">
                  </div>
                </div>
              </div>
                    {% endif %}

                {% endfor %}
            </div>
          </div>
        </div>

      </div>
    </section><!-- End Specials Section -->